<footer id="footer">
    <div class="container_12" id="footer_content">
        <div class="grid_3 centered footer_middle">
            <a href="admin_front.php">Admin home</a>
        </div>
        <div class="grid_3 centered footer_middle">
            <a href="group_reports.php">Group reports</a>
        </div>
        <div class="grid_3 centered footer_middle">
            <center><a href="list_incidents.php">View incidents</a></center>
        </div>
        <div class="grid_3 centered footer_middle">
            <a href="http://twitter.com/aptomaops">Twitter</a>
        </div>
    </div>
</footer>