<footer id="footer">
    <div class="container_12" id="footer_content">
        <div class="grid_4 centered footer_middle">
            <a href= "http://www.aptoma.com/contact">Contact</a>
        </div>
        <div class="grid_4 centered footer_middle">
            <a href= "http://www.aptoma.com/support">Support</a>
        </div>
        <div class="grid_4 centered footer_middle">
            <a href="http://twitter.com/aptomaops"><img src="img/twitter_button.png" /></a>
        </div>
    </div>
</footer>