<head>
	<meta http-equiv="Content-Type" content="text/html"; charset="utf-8" />
	<meta name="title" content="Aptoma statuspanel" />
	<link rel="stylesheet" href="css/apto_stylesheet.css" type="text/css" />
	<link rel="stylesheet" href="css/960.css" type="text/css" />
    <link rel="stylesheet" href="css/tree.css" type="text/css" />
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" type="text/css" />
	<title>Aptostat | Statuspanel for Aptoma</title>
    
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js"></script>
    
</head>